services:

    api-eventlogger:
      build: api-eventlogger/
      ports:
        - "5000:5000"

    api-fbanalyze:
      build: api-fbanalyze/
      ports:
        - "7000:5000"
    
    mongo:
        image: mongo
        container_name: mongo
        ports:
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - ./mongo:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
          ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
          ME_CONFIG_BASICAUTH: false
        depends_on:
          - mongo
